<?php

/**
 * Implements hook_theme().
 */

function weather_cast_theme() {
    return [
        'weather_cast' => [
            'variables' => [
                'description' => NULL,
                'image' => NULL,
                'temp_min' => NULL,
                'temp_max' => NULL,
                'pressure' => NULL,
                'humidity' => NULL,
                'wind'=> NULL,
                'city' => NULL
            ],
            'template' => 'myblock'
        ]
    ];
}
function mytheme_button_override_form_alter(&$form, &$form_state, $form_id) {
    global $user;
    if ($user->uid == 0) {
      if ($form_id == 'user_register_form') {
        // Change register button text.
        $form['actions']['submit']['#value'] = t('Submit!');
      }
    }
  }
