<?php

/**
 * Implements hook_theme().
 */

function weather_cast_theme() {
    return [
        'weather_cast' => [
            'variables' => [
                'description' => NULL,
                'image' => NULL,
                'temp_min' => NULL,
                'temp_max' => NULL,
                'pressure' => NULL,
                'humidity' => NULL,
                'wind'=> NULL,
                'city' => NULL
            ],
            'template' => 'myblock'
        ]
    ];
}
function mytheme_button_override_form_alter(&$form, &$form_state, $form_id) {
    global $user;
    if ($user->uid == 0) {
      if ($form_id == 'user_register_form') {
        // Change register button text.
        $form['actions']['submit']['#value'] = t('Submit!');
      }
    }
  }
/**
 * Implements hook_page_attachments.
 */
function my_module_page_attachments(array &$attachments) {
    // Add user time zone to drupalSettings.
    global $user_time,$current_user;

    //$user_time zone = new \Datetime zone($user_time zone());
    $attachments['#attached']['drupalSettings']['my_module']['user'] = [
      'time zone' => drupal_get_user_time .zone(),
    ];
    // Cache this per user.
    $attachments['#cache']['contexts'][] = 'user';
    // Clear the cache when the users is updated.
    $attachments['#cache']['tags'][] = 'user:' . $current_user->id();
  } 